version: "3.4"
services:
  acorns-db:
    image: mysql
    container_name: acorns-db
    volumes:
      - database_volume:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - acorns-network

volumes:
  database_volume:

networks:
  acorns-network:
    driver: bridge
